<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Gap Analysis Report</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            font-size: 11px;
            line-height: 1.5;
        }
        .header {
            text-align: center;
            border-bottom: 2px solid #333;
            padding-bottom: 10px;
            margin-bottom: 20px;
        }
        .header h1 {
            margin: 0;
            font-size: 18px;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 20px;
        }
        th, td {
            border: 1px solid #ddd;
            padding: 6px;
            text-align: left;
        }
        th {
            background-color: #f4f4f4;
            font-weight: bold;
            font-size: 10px;
        }
        .section-title {
            background-color: #333;
            color: white;
            padding: 8px;
            margin-top: 20px;
            margin-bottom: 10px;
        }
        .footer {
            margin-top: 30px;
            text-align: center;
            font-size: 10px;
            color: #666;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>Laporan Gap Analysis - Bezetting vs Kebutuhan</h1>
        <p>Sistem Peta Jabatan - {{ date('d F Y') }}</p>
    </div>

    <div class="section-title">
        <h2 style="margin: 0; font-size: 14px;">Jabatan Kekurangan Pegawai ({{ count($data['understaffed_positions']) }} Jabatan)</h2>
    </div>
    <table>
        <thead>
            <tr>
                <th>No</th>
                <th>Jabatan</th>
                <th>Jenis</th>
                <th>Kelas</th>
                <th>OPD</th>
                <th>Bagian</th>
                <th style="text-align: right;">Kebutuhan</th>
                <th style="text-align: right;">Bezetting</th>
                <th style="text-align: right;">Gap</th>
            </tr>
        </thead>
        <tbody>
            @foreach($data['understaffed_positions'] as $index => $item)
            <tr>
                <td>{{ $index + 1 }}</td>
                <td>{{ $item['nama_jabatan'] }}</td>
                <td>{{ $item['jenis_jabatan'] }}</td>
                <td>{{ $item['kelas'] }}</td>
                <td>{{ $item['opd'] }}</td>
                <td>{{ $item['bagian'] }}</td>
                <td style="text-align: right;">{{ $item['kebutuhan'] }}</td>
                <td style="text-align: right;">{{ $item['bezetting'] }}</td>
                <td style="text-align: right;"><strong>-{{ $item['gap'] }}</strong></td>
            </tr>
            @endforeach
        </tbody>
    </table>

    <div class="section-title">
        <h2 style="margin: 0; font-size: 14px;">Jabatan Kelebihan Pegawai ({{ count($data['overstaffed_positions']) }} Jabatan)</h2>
    </div>
    <table>
        <thead>
            <tr>
                <th>No</th>
                <th>Jabatan</th>
                <th>Jenis</th>
                <th>Kelas</th>
                <th>OPD</th>
                <th>Bagian</th>
                <th style="text-align: right;">Kebutuhan</th>
                <th style="text-align: right;">Bezetting</th>
                <th style="text-align: right;">Gap</th>
            </tr>
        </thead>
        <tbody>
            @foreach($data['overstaffed_positions'] as $index => $item)
            <tr>
                <td>{{ $index + 1 }}</td>
                <td>{{ $item['nama_jabatan'] }}</td>
                <td>{{ $item['jenis_jabatan'] }}</td>
                <td>{{ $item['kelas'] }}</td>
                <td>{{ $item['opd'] }}</td>
                <td>{{ $item['bagian'] }}</td>
                <td style="text-align: right;">{{ $item['kebutuhan'] }}</td>
                <td style="text-align: right;">{{ $item['bezetting'] }}</td>
                <td style="text-align: right;"><strong>+{{ $item['gap'] }}</strong></td>
            </tr>
            @endforeach
        </tbody>
    </table>

    <div class="footer">
        <p>Generated by SIPETA - {{ date('d F Y H:i:s') }}</p>
    </div>
</body>
</html>
