<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Analytics OPD Report</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            font-size: 12px;
            line-height: 1.6;
        }
        .header {
            text-align: center;
            border-bottom: 2px solid #333;
            padding-bottom: 10px;
            margin-bottom: 20px;
        }
        .header h1 {
            margin: 0;
            font-size: 20px;
        }
        .stats-grid {
            display: table;
            width: 100%;
            margin-bottom: 20px;
        }
        .stats-row {
            display: table-row;
        }
        .stats-cell {
            display: table-cell;
            width: 25%;
            padding: 10px;
            border: 1px solid #ddd;
            text-align: center;
        }
        .stats-cell h3 {
            margin: 0 0 5px 0;
            font-size: 12px;
            color: #666;
        }
        .stats-cell p {
            margin: 0;
            font-size: 20px;
            font-weight: bold;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 20px;
        }
        th, td {
            border: 1px solid #ddd;
            padding: 8px;
            text-align: left;
        }
        th {
            background-color: #f4f4f4;
            font-weight: bold;
        }
        .footer {
            margin-top: 30px;
            text-align: center;
            font-size: 10px;
            color: #666;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>Laporan Analytics OPD</h1>
        <h2 style="margin: 5px 0;">{{ $data['opd']->nama }}</h2>
        <p>{{ date('d F Y') }}</p>
    </div>

    <h2>Statistik OPD</h2>
    <div class="stats-grid">
        <div class="stats-row">
            <div class="stats-cell">
                <h3>Total Bagian</h3>
                <p>{{ $data['total_bagian'] }}</p>
            </div>
            <div class="stats-cell">
                <h3>Total Jabatan</h3>
                <p>{{ $data['total_jabatan'] }}</p>
            </div>
            <div class="stats-cell">
                <h3>Kebutuhan</h3>
                <p>{{ $data['total_kebutuhan'] }}</p>
            </div>
            <div class="stats-cell">
                <h3>Bezetting</h3>
                <p>{{ $data['total_bezetting'] }}</p>
            </div>
        </div>
    </div>

    <h2>Data per Bagian</h2>
    <table>
        <thead>
            <tr>
                <th>Bagian</th>
                <th style="text-align: right;">Kebutuhan</th>
                <th style="text-align: right;">Bezetting</th>
                <th style="text-align: right;">Selisih</th>
            </tr>
        </thead>
        <tbody>
            @foreach($data['bagians_data'] as $bagian)
            <tr>
                <td>{{ $bagian['nama'] }}</td>
                <td style="text-align: right;">{{ $bagian['kebutuhan'] }}</td>
                <td style="text-align: right;">{{ $bagian['bezetting'] }}</td>
                <td style="text-align: right;">{{ $bagian['selisih'] > 0 ? '+' : '' }}{{ $bagian['selisih'] }}</td>
            </tr>
            @endforeach
        </tbody>
    </table>

    <h2>Jabatan Kosong</h2>
    <table>
        <thead>
            <tr>
                <th>No</th>
                <th>Jabatan</th>
                <th>Jenis</th>
                <th>Kelas</th>
                <th>Bagian</th>
                <th style="text-align: right;">Kebutuhan</th>
            </tr>
        </thead>
        <tbody>
            @forelse($data['jabatan_kosong'] as $index => $jabatan)
            <tr>
                <td>{{ $index + 1 }}</td>
                <td>{{ $jabatan['nama_jabatan'] }}</td>
                <td>{{ $jabatan['jenis_jabatan'] }}</td>
                <td>{{ $jabatan['kelas'] }}</td>
                <td>{{ $jabatan['bagian'] }}</td>
                <td style="text-align: right;">{{ $jabatan['kebutuhan'] }}</td>
            </tr>
            @empty
            <tr>
                <td colspan="6" style="text-align: center;">Semua jabatan sudah terisi</td>
            </tr>
            @endforelse
        </tbody>
    </table>

    <div class="footer">
        <p>Generated by SIPETA - {{ date('d F Y H:i:s') }}</p>
    </div>
</body>
</html>
