<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Analytics Overview Report</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            font-size: 12px;
            line-height: 1.6;
        }
        .header {
            text-align: center;
            border-bottom: 2px solid #333;
            padding-bottom: 10px;
            margin-bottom: 20px;
        }
        .header h1 {
            margin: 0;
            font-size: 20px;
        }
        .stats-grid {
            display: table;
            width: 100%;
            margin-bottom: 20px;
        }
        .stats-row {
            display: table-row;
        }
        .stats-cell {
            display: table-cell;
            width: 25%;
            padding: 10px;
            border: 1px solid #ddd;
            text-align: center;
        }
        .stats-cell h3 {
            margin: 0 0 5px 0;
            font-size: 14px;
            color: #666;
        }
        .stats-cell p {
            margin: 0;
            font-size: 24px;
            font-weight: bold;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 20px;
        }
        th, td {
            border: 1px solid #ddd;
            padding: 8px;
            text-align: left;
        }
        th {
            background-color: #f4f4f4;
            font-weight: bold;
        }
        .footer {
            margin-top: 30px;
            text-align: center;
            font-size: 10px;
            color: #666;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>Laporan Analytics Overview</h1>
        <p>Sistem Peta Jabatan - {{ date('d F Y') }}</p>
    </div>

    <h2>Statistik Keseluruhan</h2>
    <div class="stats-grid">
        <div class="stats-row">
            <div class="stats-cell">
                <h3>Total OPD</h3>
                <p>{{ $data['stats']['total_opd'] }}</p>
            </div>
            <div class="stats-cell">
                <h3>Total Jabatan</h3>
                <p>{{ $data['stats']['total_jabatan'] }}</p>
            </div>
            <div class="stats-cell">
                <h3>Total ASN</h3>
                <p>{{ $data['stats']['total_asn'] }}</p>
            </div>
            <div class="stats-cell">
                <h3>Persentase Pemenuhan</h3>
                <p>{{ number_format($data['stats']['persentase_pemenuhan'], 1) }}%</p>
            </div>
        </div>
    </div>

    <h2>Top 10 OPD - Bezetting vs Kebutuhan</h2>
    <table>
        <thead>
            <tr>
                <th>OPD</th>
                <th style="text-align: right;">Kebutuhan</th>
                <th style="text-align: right;">Bezetting</th>
                <th style="text-align: right;">Selisih</th>
            </tr>
        </thead>
        <tbody>
            @foreach($data['topOpd'] as $opd)
            <tr>
                <td>{{ $opd['nama'] }}</td>
                <td style="text-align: right;">{{ $opd['kebutuhan'] }}</td>
                <td style="text-align: right;">{{ $opd['bezetting'] }}</td>
                <td style="text-align: right;">{{ $opd['selisih'] > 0 ? '+' : '' }}{{ $opd['selisih'] }}</td>
            </tr>
            @endforeach
        </tbody>
    </table>

    <h2>Top 10 Jabatan dengan Kekurangan Pegawai</h2>
    <table>
        <thead>
            <tr>
                <th>Jabatan</th>
                <th>Jenis</th>
                <th>OPD</th>
                <th style="text-align: right;">Kebutuhan</th>
                <th style="text-align: right;">Bezetting</th>
                <th style="text-align: right;">Gap</th>
            </tr>
        </thead>
        <tbody>
            @foreach($data['understaffed'] as $item)
            <tr>
                <td>{{ $item['nama_jabatan'] }}</td>
                <td>{{ $item['jenis_jabatan'] }}</td>
                <td>{{ $item['opd'] }}</td>
                <td style="text-align: right;">{{ $item['kebutuhan'] }}</td>
                <td style="text-align: right;">{{ $item['bezetting'] }}</td>
                <td style="text-align: right;">-{{ $item['gap'] }}</td>
            </tr>
            @endforeach
        </tbody>
    </table>

    <div class="footer">
        <p>Generated by SIPETA - {{ date('d F Y H:i:s') }}</p>
    </div>
</body>
</html>
